services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
      - PORT=5000
    ports:
      - "80:5000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
